#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
FTXUI amalgamation generator.

Inlines every FTXUI public header, internal header and (non-test) source file
into a single self-contained header: ftxui_amalgamation.hpp.

Rules:
  * `#include "ftxui/..."` / `#include <ftxui/...>` / internal relative headers
    are resolved against include/ and src/ and inlined exactly once.
  * System `#include <...>` lines are LEFT IN PLACE (they carry their own include
    guards, so duplicates are harmless, and keeping them in place preserves any
    surrounding platform `#if defined(...)` guards, e.g. <sys/ioctl.h>).
  * *_test.cpp / *_fuzzer.cpp / *benchmark* files are skipped.

FTXUI is MIT licensed (Copyright (c) 2019 Arthur Sonzogni).
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FT   = os.path.join(ROOT, "FTXUI-4.1.1")
INC  = os.path.join(FT, "include")
SRC  = os.path.join(FT, "src")
OUT  = os.path.join(ROOT, "ftxui_amalgamation.hpp")

SEARCH_DIRS = [INC, SRC]
INC_RE = re.compile(r'^\s*#\s*include\s*([<"])([^>"]+)[>"]')

# Per-file renames of file-private symbols that would otherwise clash once every
# translation unit is merged into one. Keyed by path relative to FT root.
# Each entry maps an old identifier to a unique new identifier (whole-word).
RENAMES = {
    "src/ftxui/dom/graph.cpp": {"charset": "charset_graph"},
}

visited = set()
body = []


def is_excluded(name: str) -> bool:
    n = name.lower()
    return ("_test.cpp" in n or "_fuzzer.cpp" in n or "benchmark" in n)


def resolve(name: str):
    for d in SEARCH_DIRS:
        p = os.path.join(d, name.replace("/", os.sep))
        if os.path.isfile(p):
            return os.path.normpath(p)
    return None


def process(path: str):
    path = os.path.normpath(path)
    if path in visited:
        return
    visited.add(path)
    rel = os.path.relpath(path, FT).replace(os.sep, "/")
    with open(path, "r", encoding="utf-8") as f:
        lines = f.readlines()
    renames = RENAMES.get(rel, {})
    body.append(f"\n// ===== BEGIN {rel} =====\n")
    for line in lines:
        m = INC_RE.match(line)
        if m:
            name = m.group(2)
            target = resolve(name)
            if target is not None:
                process(target)          # inline internal header (once)
                continue
            # system header: keep in place (preserves #ifdef guards)
        for old, new in renames.items():
            line = re.sub(r'\b' + re.escape(old) + r'\b', new, line)
        body.append(line)
    body.append(f"// ===== END {rel} =====\n")


def collect_sources():
    srcs = []
    for sub in ("screen", "dom", "component"):
        d = os.path.join(SRC, "ftxui", sub)
        for fn in sorted(os.listdir(d)):
            if fn.endswith(".cpp") and not is_excluded(fn):
                srcs.append(os.path.join(d, fn))
    return srcs


def main():
    for cpp in collect_sources():
        process(cpp)

    header = []
    header.append("// =====================================================================\n")
    header.append("// ftxui_amalgamation.hpp - single-header build of FTXUI 4.1.1\n")
    header.append("// Auto-generated by tools/amalgamate_ftxui.py. DO NOT EDIT BY HAND.\n")
    header.append("//\n")
    header.append("// FTXUI - https://github.com/ArthurSonzogni/FTXUI\n")
    header.append("// The MIT License (MIT)\n")
    header.append("// Copyright (c) 2019 Arthur Sonzogni.\n")
    header.append("//\n")
    header.append("// Permission is hereby granted, free of charge, to any person obtaining a copy\n")
    header.append('// of this software and associated documentation files (the "Software"), to deal\n')
    header.append("// in the Software without restriction, including without limitation the rights\n")
    header.append("// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n")
    header.append("// copies of the Software, and to permit persons to whom the Software is\n")
    header.append("// furnished to do so, subject to the following conditions:\n")
    header.append("//\n")
    header.append("// The above copyright notice and this permission notice shall be included in\n")
    header.append("// all copies or substantial portions of the Software.\n")
    header.append("//\n")
    header.append('// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. See the\n')
    header.append("// full text in FTXUI-4.1.1/LICENSE.\n")
    header.append("// =====================================================================\n")
    header.append("#ifndef FTXUI_AMALGAMATION_HPP\n")
    header.append("#define FTXUI_AMALGAMATION_HPP\n\n")

    with open(OUT, "w", encoding="utf-8") as f:
        f.writelines(header)
        f.writelines(body)
        f.write("\n#endif  // FTXUI_AMALGAMATION_HPP\n")

    print(f"Files inlined : {len(visited)}")
    print(f"Output        : {OUT}")
    print(f"Size          : {os.path.getsize(OUT)} bytes")


if __name__ == "__main__":
    main()
